# This file substitutes the command section below in the docker-compose.yml file for the Traefik container.
    # command:
    #   - --api.insecure=true
    #   - --api.dashboard=true
    #   - --providers.docker
    #   - --entrypoints.web.address=:80

global:
  checkNewVersion: true
  sendAnonymousUsage: false
log:
  level: DEBUG
api:
  dashboard: true
  insecure: true # DO NOT USE THIS IN PRODUCTION
entryPoints:
  web:
    address: ":80" # tcp trafic for http
  # websecure:
  #   address: ":443" # tcp trafic for https
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock" # To allow dynamic configurtion inside Docker -> allows redirect using traefik routers
